name: Consumer

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://solenersync.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  REACT_APP_API_BASE_URL: http://localhost:3000
  GIT_COMMIT: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pact_provider: [
            'user-store',
            'solar-array-store'
            'pv-service'
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install
        run: npm i
      - name: Test
        env:
          PACT_PROVIDER: ${{ matrix.pact_provider }}
        run: make test
      - name: Publish pacts between ses-front-end and ${{ matrix.pact_provider }}
        run: GIT_BRANCH=${GIT_REF:11} make publish_pacts
        env:
          PACT_PROVIDER: ${{ matrix.pact_provider }}

  # Runs on branches as well, so we know the status of our PRs
  # can-i-deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: docker pull pactfoundation/pact-cli:latest
  #     - name: Can I deploy?
  #       run: GIT_BRANCH=${GIT_REF:11} make can_i_deploy