name: Test consumer - on push to PR
on:
  pull_request:
    branches:
      - main
env:
  PACT_BROKER_BASE_URL: https://solenersync.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  VERSION: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 📦️ Install
        run: npm i
      - name: 🧪 Test and upload to PactFlow 📈
        run: BRANCH=${GITHUB_REF:11} make test_and_publish

  # Runs on branches as well, so we know the status of our PRs
  can-i-deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: 🛂 Can I deploy?
        run: BRANCH=${GITHUB_REF:11} make can_i_deploy

  # Only deploy from main
  deploy:
    runs-on: ubuntu-latest
    needs: [can-i-deploy]
    steps:
      - uses: actions/checkout@v3
      - name: 🚀 Deploy
        run: BRANCH=${GITHUB_REF:11} make deploy
        if: github.ref == 'refs/heads/main'