name: End to End

on:
  repository_dispatch:
    types: [pod_updated]

jobs:
  test:
    name: Production tests
    runs-on: ubuntu-latest

    env:
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install
        run: |
          npm ci
      - name: Cypress Tests
        run: |
            npm run cypress:run
            echo "TEST_RESULT=$?" >> $GITHUB_ENV
        id: cypress_tests
        continue-on-error: true

      - name: Slack notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_RELEASES}}
          SLACK_COLOR: | 
            ${{ env.TEST_RESULT == '0' && 'good' || 'danger' }}
          SLACK_MESSAGE: |
            'A new version of ${{ github.event.client_payload.container_name }} is available. \nProduction testing was *${{ env.TEST_RESULT == '0' && 'successful' || 'a failure' }}* for version ${{ github.event.client_payload.version_number }}'
          SLACK_USERNAME: notifier
          SLACK_ICON_EMOJI: ":github:"




