name: End to End

on:
  repository_dispatch:
    types: [pod_updated]

jobs:
  test:
    name: Production tests
    runs-on: ubuntu-latest

    env:
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install
        run: |
          npm ci
      - name: Cypress Tests
        run: npm run cypress:run
        id: cypress_tests
        continue-on-error: true

      - name: Slack notification on success
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ steps.cypress_tests.outcome }}
          text: 'A new version of ${{ github.event.client_payload.container_name }} is available. \nProduction tests have succeeded for version ${{ github.event.client_payload.version_number }}'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack notification on failure
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ steps.cypress_tests.outcome }}
          text: 'A new version of ${{ github.event.client_payload.container_name }} is available. \nProduction tests have failed for version ${{ github.event.client_payload.version_number }}'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}




