name: CI Tests

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Integration
    runs-on: ubuntu-latest
    env:
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
      NEXTAUTH_SECRET: ${{ secrets.TEST_USER_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install
        run: |
          npm ci
      # - name: Jest Unit Tests
      #   run: npm test
      - name: Cypress Tests
        run: npm run test:e2e:run
