name: End to End

on:
  repository_dispatch:
    types: [pod_updated]

jobs:
  test:
    name: Production tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install
        run: |
          npm ci

      - name: Cypress Tests
        run: npm run cypress:run
